#!/bin/sh

# Place in /etc/motd.d and drop the .sh suffix.

#echo -e "\n\033[1mWelcome to Gentoo Linux!\033[0m"
#linux_logo -L 2

echo -e "This server is maintained by \033[1m$(cat /etc/maintainer)\033[0m. (\033[1m$(cat /etc/maintainer-address)\033[0m)."
echo "This system uses Romans My-Gentoo-Misc repsoitory (https://github.com/romaninsh/my-gentoo-misc)"

MAX=$(($(cat /proc/cpuinfo | grep processor | wc -l) - 1))
LOAD=$(cat /proc/loadavg | cut -d '.' -f 1)

if [ $LOAD -gt $(($MAX * 4)) ]
then echo -en " \033[1;31m*\033[0m"
elif [ $LOAD -gt $MAX ]
then echo -en " \033[1;33m*\033[0m"
else echo -en " \033[1;32m*\033[0m"
fi
uptime

